# This dockerfile is for Centaur Emacs
# VERSION 1.1.0
# Author: Vincent Zhang <seagle0128@gmail.com>
# Command format: Instruction [arguments / command] ..

# Base image to use
FROM ubuntu

# Commands to update the image
RUN cp /etc/apt/sources.list /etc/apt/sources.list.bak
RUN sed -i "s/archive.ubuntu.com/mirrors.aliyun.com/g" /etc/apt/sources.list
RUN apt-get update
RUN apt-get upgrade -y
RUN apt-get install -y software-properties-common

# Install Centaur Emacs
RUN add-apt-repository -y ppa:kelleyk/emacs
RUN apt-get update
RUN apt-get install -y emacs-nox git
RUN git clone --depth 1 https://github.com/seagle0128/.emacs.d.git ~/.emacs.d

ENV TERM xterm-256color
WORKDIR /root
